---
- name: Remove CrowdStrike Installer
  block:
    - name: Check if Crowdstrike Installer file exists in Debian
      stat:
        path: "{{ ansible_env.HOME }}/{{ installer_debian }}"
      register: debian_file_stat
      when: ansible_facts['distribution'] == "Debian"

    - name: Clean-up Crowdstrike Installer file in Debian
      file:
        path: "{{ ansible_env.HOME }}/{{ installer_debian }}"
        state: absent
      when: debian_file_stat.stat.exists
      failed_when: not debian_file_stat.stat.exists

    - name: Check if Crowdstrike Installer file exists in Non Debian
      stat:
        path: "{{ ansible_env.HOME }}/{{ installer_others }}"
      register: non_debian_file_stat
      when: (ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")

    - name: Clean-up Crowdstrike Installer file in Non Debian
      file:
        path: "{{ ansible_env.HOME }}/{{ installer_others }}"
        state: absent
      when: non_debian_file_stat.stat.exists
      failed_when: not non_debian_file_stat.stat.exists
  tags: cleanup