- name: Delete Installer from Temp Directory
  win_file:
    path: "{{ local_path_windows }}\\{{ crowdstrike_win_exe }}"
    state: absent
  register: installer_removed
  tags: cleanup

- name: Write cleanup result to stdout
  debug:
    msg: "cleaned_up: {{ installer_removed.changed | default(false) }}"
  when: installer_removed is defined
  tags: cleanup
