# Stop CrowdStrike Falcon Sensor Service
- name: Stop CrowdStrike Falcon Sensor Service
  win_service:
    name: "{{ windows_crowdstrike_service_name }}"
    state: stopped
  register: service_stop_result
  until: service_stop_result is not failed
  retries: 3
  delay: 60
  tags: restart

- name: Pause for 30 seconds
  pause:
    seconds: 30

# Restart CrowdStrike Falcon Sensor Service
- name: Restart CrowdStrike Falcon Sensor Service
  win_service:
    name: "{{ windows_crowdstrike_service_name }}"
    state: started
  register: service_restart_result
  until: service_restart_result is not failed
  retries: 3
  delay: 60
  ignore_errors: true
  when:
  - service_stop_result is defined
  - service_stop_result.state == "stopped"
  tags: restart

- name: Write CrowdStrike Service restart status to stdout
  debug:
    msg: "crowdstrike_restarted_status: {{ 'successfully restarted' if service_restart_result.failed == false else 'failed to restart' }}"
  when: service_restart_result is defined
  tags: restart
