- name: Start Crowdstrike Service
  win_service:
    name: "{{ windows_crowdstrike_service_name }}"
    state: started
  register: service_started
  until: service_started is not failed
  retries: 3
  delay: 60
  ignore_errors: true
  tags: start

- name: Validate Service started
  assert:
    that:
    - service_started.state == "running" or service_started.changed == true
    fail_msg: "Crowdstrike service fails to start"
    success_msg: "Crowdstrike service successfully started"
  ignore_errors: true
  register: service_start_result
  tags: start

- name: Write CrowdStrike Service start status to stdout
  debug:
    msg: "crowdstrike_running: {{ 'true' if service_start_result.failed == false else 'false' }}"
  when: service_start_result is defined
  tags: start
