- name: Configure Crowdstrike
  command: /opt/CrowdStrike/falconctl -s -f --cid={{ crowdstrike_cid }}
  register: crowdstrike_configured
  tags: configure

- name: Write CrowdStrike Configuration Status to stdout
  debug:
    msg: "crowdstrike_configured: {{ 'true' if crowdstrike_configured.rc == 0 else 'false' }}"
  when: crowdstrike_configured is defined
  tags: configure
