# This playbook is used to start the CrowdStrike service on Linux systems
- name: Gather service facts
  service_facts:
  register: service_facts
  tags: install

# Start CrowdStrike Service
- name: Start CrowdStrike Service
  block:
  - name: Enable and Restart CrowdStrike Service
    service:
      name: "{{ linux_crowdstrike_service_name }}"
      enabled: true
      state: restarted
    register: service_started
    # when: service_facts.ansible_facts.services[linux_cs_service].state == "stopped"
  when: service_facts is defined
  tags: start

  rescue:
  - name: Write error message to stdout
    debug:
      msg: "Failed to start CrowdStrike Service"
    tags: start

# Write service start status to stdout
- name: Write CrowdStrike Service start status to stdout
  debug:
    msg: "crowdstrike_running: {{ service_started.changed | default(false) }}"
  when: service_started is defined
  tags: start
