--- 
- name: Crowdstrike | Init Install | Get Instance Name/Host Name
  set_fact:
    crowdstrike_hostname: "{{ hostvars[inventory_hostname]['tags']['Name'] }}"

- name: Crowdstrike | Init Install | Display VAR crowdstrike_hostname
  debug: var=crowdstrike_hostname

- name: Crowdstrike | Init Install | Get First 2 characters of Host Name
  set_fact:
    crowdstrike_grouping_identifier: "{{ crowdstrike_hostname[0:2] }}"

- name: Crowdstrike | Init Install | Display VAR crowdstrike_grouping_identifier
  debug: var=crowdstrike_grouping_identifier

- name: Crowdstrike | Init Install | Set Grouping = Shared Services
  set_fact:
    crowdstrike_grouping_product: "SharedServices"
    crowdstrike_grouping_region: "us-gov-east-1"
  when: crowdstrike_grouping_identifier == "en"

- name: Crowdstrike | Init Install | Set Grouping = Shared Services
  set_fact:
    crowdstrike_grouping_product: "SharedServices"
    crowdstrike_grouping_region: "us-gov-east-1"
  when: crowdstrike_grouping_identifier == "en"

- name: Crowdstrike | Init Install | Set Grouping = SharedServices / us-east-1
  set_fact:
    crowdstrike_grouping_product: "SharedServices"
    crowdstrike_grouping_region: "us-east-1"
  when: crowdstrike_grouping_identifier == "cu"
