---
- name: Check if Crowdstrike service is installed on Windows
  win_service:
    name: CSFalconService
  register: service_info

- name: Get Crowdstrike from S3 Bucket
  win_shell: |
    Copy-S3Object -BucketName {{ software_bucket }} -Region {{ aws_region }} -Key {{ crowdstrike_win_exe }} -LocalFolder {{ ansible_env.TEMP }}
  args:
    creates: "{{ ansible_env.TEMP }}\\{{ crowdstrike_win_exe }}"
  when: not service_info.exists

- name: Install Crowdstrike on Windows
  become: true
  become_method: runas
  become_user: SYSTEM
  win_package:
    path: "{{ ansible_env.TEMP }}\\{{ crowdstrike_win_exe }}"
    state: present
    creates_service: CSFalconService
    arguments: "/install /quiet CID={{ crowdstrike_cid }} {{ falcon_windows_install_args }}"
  when: not service_info.exists
  register: cs_windows
  until: cs_windows is not failed
  retries: 3
  delay: 60

- name: Start Crowdstrike Service if not Running in Windows
  win_service:
    name: CSFalconService
    state: started
  when: 
    - service_info.state is defined
    - service_info.state != "running"
  register: cs_start
  until: cs_start is not failed
  retries: 3
  delay: 60
  # register: service_start
  # when: not service_result is search("RUNNING")

- name: Delete Installer from Temp Directory
  win_file:
    path: "{{ ansible_env.TEMP }}\\{{ crowdstrike_win_exe }}"
    state: absent