---
# Check if crowdstrike is installed (Windows)
- name: Check if CrowdStrike is installed
  win_service: 
    name: "{{ windows_crowdstrike_service_name }}"
  register: result
  tags: status

- name: Set fact based on CrowdStrike Service install status
  set_fact:
    crowdstrike_installed: "{{ result.exists }}"
  tags: status

- name: Write CrowdStrike Service install status to stdout 
  debug:
    var: crowdstrike_installed
  tags: status