# Check if crowdstrike is installed (Linux)
- name: Gather service facts
  service_facts:
  register: service_facts
  tags: install

- name: Write CrowdStrike Service install status to stdout
  debug:
    msg: "crowdstrike_installed: {{ 'true' if linux_cs_service in service_facts.ansible_facts.services else 'false' }}"
  when: service_facts is defined
  tags: status
