- name: Get service facts
  service_facts:
  register: service_facts
  tags: status

- name: Write CrowdStrike Service running status to stdout
  debug:
    msg: "crowdstrike_running: {{ 'true' if service_facts.ansible_facts.services[linux_cs_service].state == 'running' else 'false' }}"
  when: linux_cs_service in service_facts.ansible_facts.services
  tags: status

- name: Write CrowdStrike Service not running status to stdout
  debug:
    msg: "crowdstrike_running: false"
  when: linux_cs_service not in service_facts.ansible_facts.services
  tags: status
