# Check if crowdstrike is installed (Windows)
- name: Check if CrowdStrike is installed
  win_service:
    name: "{{ windows_crowdstrike_service_name }}"
  register: result
  tags: status

- name: Write CrowdStrike Service install status to stdout
  debug:
    msg: "crowdstrike_installed: {{ result.exists }}"
  when: result is defined
  tags: status
