# Check if crowdstrike is running (Windows)
- name: Check if CrowdStrike is running
  win_service:
    name: "{{ windows_crowdstrike_service_name }}"
    state: started
  register: result
  tags: status

- name: Write CrowdStrike running Status to stdout
  debug:
    msg: "crowdstrike_running_state: {{ result.state }}"
  when: result is defined
  tags: status
