---
#Check init system of the Linux machine
- name: Check if Systemd is being used
  command: systemctl --version
  become_user: sudo
  remote_user: "{{ ansible_user }}"
  register: systemd_result
  tags: restart

#Restart crowdstrike with init system of the Linux machine
- name: Restart CrowdStrike Service
  block:
    - name: Restart CrowdStrike Falcon Sensor Service with Systemd
      systemd:
        name: "{{ crowdstrike_service_name }}"
        state: restarted
      register: service_restart_result
      until: service_restart_result is not failed
      retries: 3
      delay: 60
      when: systemd_result.rc == 0

    - name: Restart CrowdStrike Falcon Sensor Service with SysVinit
      service:
        name: "{{ crowdstrike_service_name }}"
        state: restarted
      register: service_restart_result
      until: service_restart_result is not failed
      retries: 3
      delay: 60
      when: systemd_result.rc != 0

    - debug:
        msg: "CrowdStrike Restart Status: {{ service_restart_result.stdout }}"
  when: systemd_result.exists
  tags: status

- name: Crowdstrike restart status (Linux)
  set_fact:
    is_crowdstrike_restarted: "{{ service_restart_result.exists }}"
    is_crowdstrike_not_restarted: "{{ not service_restart_result.exists }}"
  tags: always