---
#Update the current state of the incident in servicenow to 'in-progress'
- name: Update the incident in servicenow
  incident:
    instance:
      #Basic authentication to the servicenow instance
      host: "{{ sn_host }}"
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      #OAUTH authentication to the servicenow instance
      grant_type: "{{ sn_grant_type }}"
      access_token: "{{ sn_access_token }}"
      client_id: "{{ sn_client_id }}"
      client_secret: "{{ sn_client_secret }}"
    state: resolved
    number: "{{ incident_number }}"
    close_code: "Solved (Permanently)"
    close_notes: "{{ comments }}"
  register: ticket_update_result
  delegate_to: localhost
  tags: resolve

- name: Set fact for the snow ticket state
  set_fact:
    ticket_state_resolved: "{{ ticket_update_result.incident.state }}"
  when: ticket_update_result.exists
  tags: always