---
# Check if crowdstrike is installed (Linux)
- name: Check if CrowdStrike is installed
  become_method: sudo
  remote_user: "{{ ansible_user }}"
  stat:
    path: /opt/CrowdStrike/falconctl
  register: crowdstrike_installed_output
  failed_when: not crowdstrike_installed_output.stat.exists
  tags: status