---
- name: Get Crowdstrike from S3 Bucket
  win_shell: |
    Copy-S3Object -BucketName {{ software_bucket }} -Region {{ aws_region }} -Key {{ crowdstrike_win_exe }} -LocalFolder {{ ansible_env.TEMP }}
  args:
    creates: "{{ ansible_env.TEMP }}\\{{ crowdstrike_win_exe }}"
  register: result
  failed_when: result.rc != 0
  tags: download
  
- name: Install Crowdstrike on Windows
  become: true
  become_method: runas
  become_user: SYSTEM
  win_package:
    path: "{{ ansible_env.TEMP }}\\{{ crowdstrike_win_exe }}"
    state: present
    creates_service: "{{ crowdstrike_service_name }}"
    arguments: "/install /quiet CID={{ crowdstrike_cid }} {{ falcon_windows_install_args }}"
  register: service_installed
  until: service_installed is not failed
  retries: 3
  delay: 60
  tags: install