---
#For Linux
- name: Print OS type for Linux
  debug:
    msg: "{{ Linux | to_json }}"
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Suse"

#For Windows
- name: Print OS type for Windows
  debug:
    msg: "{{ Windows | to_json }}"
  when: ansible_facts['os_family'] == "Windows"