---
#Using ansible URI to make an API call to PagerDuty to retrieve on-call information
- name: Get the ID of who is on-call from INFRA-SRE in PagerDuty
  uri:
    url: "https://api.pagerduty.com/oncalls?service_ids={{ pagerduty_service_id }}"
    method: GET
    headers:
      Accept: "application/vnd.pagerduty+json;version=2"
      Authorization: "Token token={{ pagerduty_api_token }}"
      Content-Type: "application/json"
    return_content: true
    register: on_call_api_response
  tags: oncall

- name: Extract on-call user information and set as a fact(URI)
  set_fact:
    on_call_user_id: "{{ on_call_api_response.json.oncalls[0].user.id }}"
  tags: oncall

#Using ansible URI to create an incident in PagerDuty and assign to the on-call user
- name: Create incident and assign to on-call user
  uri:
    url: https://api.pagerduty.com/incidents
    method: POST
    headers:
      Accept: "application/vnd.pagerduty+json;version=2"
      Authorization: "Token token={{ pagerduty_api_token }}"
      Content-Type: "application/json"
      From: "{{ pagerduty_user_email }}"
    body_format: json
    body:
      incident:
        type: "incident"
        title: "{{ short_description }}"
        service:
          id: "{{ service_id }}"
          type: "service_reference"
        priority:
          id: "{{ priority_id }}"
          type: "priority_reference"
        urgency: "high"
        incident_key: "{{ incident_key }}"
        body:
          type: "incident_body"
          details: "{{ long_description }}"
        escalation_policy:
          id: "{{ escalation_policy_id }}"
          type: "escalation_policy_reference"
        assignments:
          - assignee:
              id: "{{ on_call_user_id }}"
              type: "user_reference"
  register: incident_created
  debug:
    msg: "PagerDuty Alert Status: {{ incident_created.json.incident.status }}"
  delegate_to: localhost
  tags: pageoncall
