---
- name: Download CrowdStrike Installer
  block:
    - name: Download Crowdstrike Installer file for Debian
      become: true
      remote_user: "{{ ansible_user }}"
      aws_s3:
        region: "{{ aws_region }}"
        mode: get
        bucket: "{{ s3_location }}"
        object: "software/{{ installer_debian }}"
        dest: "{{ ansible_env.HOME }}/{{ installer_debian }}"
        overwrite: different
      when: (ansible_facts['distribution'] == "Debian")

    - name: Download Crowdstrike Installer file for Non Debian
      become: true
      remote_user: "{{ ansible_user }}"
      aws_s3:
        region: "{{ aws_region }}"
        mode: get
        bucket: "{{ s3_location }}"
        object: "software/{{ installer_others }}"
        dest: "{{ ansible_env.HOME }}/{{ installer_others }}"
        overwrite: different
      when: (ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")
  tags: download

- name: Check if CrowdStrike installer files were downloaded
  block:
    - name: Check if Crowdstrike files were downloaded for Debian
      stat:
        path: "{{ ansible_env.HOME }}/{{ installer_debian }}"
      register: debian_file_downloaded
      when: (ansible_facts['distribution'] == "Debian")

    - name: Check if Crowdstrike files were downloaded for Non Debian
      stat:
        path: "{{ ansible_env.HOME }}/{{ installer_others }}"
      register: non_debian_file_downloaded
      when: ((ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon"))

- name: Set fact based on CrowdStrike Installer files download status
  block:
    - name: Set fact based on files download status for Debian
      set_fact:
        installer_files_download_failed: true
      when: (ansible_facts['distribution'] == "Debian") and not debian_file_downloaded.stat.exists

    - name: Set fact based on files download status for Non Debian
      set_fact:
        installer_files_download_failed: true
      when: ((ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")) and not non_debian_file_downloaded.stat.exists
  tags: download

- name: Install CrowdStrike
  block:
    - name: Install Crowdstrike for Debian
      command: dpkg -i {{ installer_debian }}
      become: true
      become_method: sudo
      remote_user: "{{ ansible_user }}"
      args:
        chdir: "{{ ansible_env.HOME }}"
      register: crowdstrike_installed
      debug:
        msg: crowdstrike_installed
      when: 
        - not installer_files_download_failed
        - (ansible_facts['distribution'] == "Debian")
      
    - name: Install Crowdstrike for RHEL, Oracle, CentOS and Amazon Linux
      command: yum install {{ installer_others }}
      become: true
      become_method: sudo
      remote_user: "{{ ansible_user }}"
      args:
        chdir: "{{ ansible_env.HOME }}"
      register: crowdstrike_installed
      debug:
        msg: crowdstrike_installed
      when: 
        - not installer_files_download_failed
        - (ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")
  tags: install

- name: Configure Crowdstrike
  command: /opt/CrowdStrike/falconctl -s -f --cid={{ crowdstrike_cid }} --tags="{{ crowdstrike_grouping_product }},{{ crowdstrike_grouping_region }}"
  become: true
  become_method: sudo
  remote_user: "{{ ansible_user }}"
  register: crowdstrike_configured
  debug:
    msg: crowdstrike_configured
  when: crowdstrike_installed.exists
  tags: configure

- name: Check if Systemd is being used
  command: systemctl --version
  become_user: sudo
  remote_user: "{{ ansible_user }}"
  register: systemd_result
  tags: start

- name: Start CrowdStrike Service
  block:
    - name: Start Crowdstrike Service when init system is SysVinit i.e not Systemd
      command: service {{ crowdstrike_service_name }} start
      become: true
      become_method: sudo
      remote_user: "{{ ansible_user }}"
      when: systemd_result.rc != 0
      register: service_started

    - name: Start Crowdstrike Service when init system is Systemd
      command: systemctl start {{ crowdstrike_service_name }}
      become: true
      become_method: sudo
      remote_user: "{{ ansible_user }}"
      when: systemd_result.rc == 0
      register: service_started

    - debug:
        msg: "CrowdStrike Service Start Status: {{ service_started.stdout }}"
  when: systemd_result.exists
  tags: start

- name: Remove CrowdStrike Installer
  block:
    - name: Clean-up Crowdstrike Installer file in Debian
      file:
        path: "{{ ansible_env.HOME }}/{{ installer_debian }}"
        state: absent
      when: (ansible_facts['distribution'] == "Debian")

    - name: Clean-up Crowdstrike Installer file in Non Debian
      file:
        path: "{{ ansible_env.HOME }}/{{ installer_others }}"
        state: absent
      when: (ansible_facts['distribution'] == "RHEL") or (ansible_facts['distribution'] == "Oracle") or (ansible_facts['distribution'] == "CentOS") or (ansible_facts['distribution'] == "Amazon")
  when: not installer_files_download_failed
  tags: cleanup

- name: Crowdstrike Install status (Linux)
  set_fact:
    is_crowdstrike_not_installed_not_configured_and_not_running: "{{ not crowdstrike_installed.exists and not crowdstrike_configured.exists and not service_started.exists }}"
    is_crowdstrike_installed_not_configured_and_not_running: "{{ crowdstrike_installed_output.exists and not crowdstrike_configured.exists and not service_started.exists }}"
    is_crowdstrike_installed_configured_and_not_running: "{{ crowdstrike_installed_output.exists and crowdstrike_configured.exists and not service_started.exists }}"
    is_crowdstrike_installed_configured_and_running: "{{ crowdstrike_installed_output.exists and crowdstrike_configured.exists and service_started.exists }}"
  tags: always
