---
- name: Check if CrowdStrike Service is running
  hosts: all
  gather_facts: true
  become: true
  become_method: "{{ (ansible_facts['os_family'] == 'Windows') | ternary('runas', 'sudo') }}"
  become_user: "{{ svc_user }}"
  remote_user: "{{ svc_user }}"

  vars_files:
    - vars/{{ ansible_facts['os_family'] }}.yml
  
  tasks:
    - name: wait for hosts to be available
      wait_for_connection:
        connect_timeout: 60
        timeout: 900
        sleep: 60
      tags: always

    - name: Check if CrowdStrike Service is running on Linux
      include_role:
        name: ../../
        tasks_from: is_crowdstrike_running_linux
      when:
        - ansible_facts['os_family'] == "Linux"
      tags: status

    - name: Check if CrowdStrike Service is running on Windows
      include_role:
        name: ../../
        tasks_from: is_crowdstrike_running_windows
      when:
        - ansible_facts['os_family'] == "Windows"
      tags: status