---
- name: Check if CrowdStrike Service is running
  hosts: all
  gather_facts: true
  become: true
  become_method: runas
  become_user: "{{ svc_user }}"
  
  tasks:
    - name: wait for hosts to be available
      wait_for_connection:
        connect_timeout: 60
        timeout: 900
        sleep: 60
      tags: always

    - name: Check if CrowdStrike Service is running on Windows
      include_role:
        name: ../../
        tasks_from: is_crowdstrike_running_windows
      tags: status