---
- name: Remove installation files
  hosts: all
  gather_facts: true
  become: true
  become_method: runas
  become_user: "{{ svc_user }}"

  tasks:
    - name: wait for hosts to be available
      wait_for_connection:
        connect_timeout: 60
        timeout: 900
        sleep: 60
      tags: always

    - name: Remove installation files in Windows
      include_role:
        name: ../../
        tasks_from: cleanup_installation_files_windows
      tags: cleanup