---
- name: Install CrowdStrike Agent
  hosts: all
  vars_files:
    - vars/connection_info.yml
    - defaults/main.yml
  tasks:
    - name: wait for hosts to be available
      wait_for_connection:
        connect_timeout: 60
        timeout: 900
        sleep: 60
      tags: always
    
    - name: Linux Tasks
      block:
        - name: Include Linux Specific Variables
          include_vars:
            file: vars/linux.yml

        - name: Install CrowdStrike agent in Linux
          roles:
            - install_crowdstrike_linux
      when:
        - ansible_facts['os_family'] == "Linux"

    - name: Windows Tasks
      block:
        - name: Include Windows Specific Variables
          include_vars:
            file: vars/windows.yml

        - name: Install CrowdStrike agent in Linux
          roles:
            - install_crowdstrike_windows
      when:
        - ansible_facts['os_family'] == "Windows"